apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  selector:
      matchLabels:
        app: auth-service
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
{{ tuple "auth-service" . | include "werf_container_image" | indent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  clusterIP: None
  selector:
    app: auth-service
  ports:
  - name: auth-service-backend
    port: 80
    protocol: TCP

