apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-service
  labels:
    app: consumer-service
spec:
  selector:
      matchLabels:
        app: consumer-service
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer-service
    spec:
      containers:
      - name: consumer-service
{{ tuple "consumer-service" . | include "werf_container_image" | indent 8 }}

---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  labels:
    app: consumer-service
spec:
  clusterIP: None
  selector:
    app: consumer-service
  ports:
  - name: consumer-service-backend
    port: 80
    protocol: TCP

